### ISSUE TITLE
SUSE-OpenSUSE admin docs need more love

### ISSUE THREAD

**Issue by ArangoGutierrez** [sylabs/singularity-admindocs#17]
I am trying SUSE variant openSUSE leap 15, and noticed that admin docs for zypper users needs more love.

**Comment by dctrud** [comment]
Hi - @ArangoGutierrez - if you are still looking at SUSE at all, are there any particulars that need attention. I'm not a SUSE guy since the late 90s :-) so will have to dig around otherwise.

**Comment by ArangoGutierrez** [comment]
No, I am not any longer, feel free to close this issue
