### ISSUE TITLE
On-premise build server documentation

### ISSUE THREAD

**Issue by rasai** [sylabs/singularity-admindocs#21]
Hello,

Is it possible to add instructions for on-premise build server on the admindocs?

In the User docs:
https://www.sylabs.io/guides/3.0/user-guide/build_a_container.html
under build options, the description of --builder flag seems to say that it is possible to create an on-premise build server. 
I am a system admin on a medium-sized, shared-resource cluster, and we are receiving requests to build singularity containers on the cluster. As we don't want to give root access to all users on all systems, we were hoping to use the new remote build feature of 3.0 to create a dedicated build VM.
Unfortunately, I haven't been able to find any documentation on this anywhere.

Thanks in advance!

**Comment by sushma-98** [comment]
Thank you @rasai for raising this. We are in the process of writing new pages for 3.0 Admin docs. Will include this as well. 
@tri-adam would be able to help you more on this. 

In the mean time, https://cloud.sylabs.io/builder talks about using the Remote Builder from the Singularity CLI

**Comment by tri-adam** [comment]
Hi @rasai , the Sylabs team will be offering the Remote Builder for on-premise deployments in the near future. Unfortunately, because the packaging is not yet complete, we haven't documented what that will look like yet. We'd love the opportunity to discuss your requirements to make sure we hit the mark with that work. Are you on our Slack by any chance?

**Comment by rasai** [comment]
I see. Thank you both for the response! We will be looking forward to the doc and the on-premise deployment of Remote Builder. 
And thank you for he offer on the discussion, but I think it would be a bit too early. I would like to read up a little more on the remote builder first.

**Comment by sushma-98** [comment]
Sure @rasai ! And if you encounter any issues or need more documentation let us know.

**Comment by AlfWa** [comment]
Our institute (https://mdc-berlin.de/en) would like to use an on premise remote builder as well.

I would be happy to serve as an alpha/beta test site or, if you still need input, to talk about our requirements (really just: build w/o root for users).

Regards, Alf.

**Comment by RobertRosca** [comment]
EuXFEL ([https://www.xfel.eu/](https://www.xfel.eu/)) would also be interested in having an on-premise remote builder.

Is there an estimate on when the first versions of the builder will be made public?

Cheers,

Robert

**Comment by sushma-4** [comment]
Hi Robert,

Thank you for showing interest. Would you please let our team know about it here: https://sylabs.io/contact-us/

**Comment by ChrisPattison** [comment]
Is there any update to this?

**Comment by sushma-4** [comment]
@dctrud might know...

**Comment by dctrud** [comment]
Hello. The remote builder is part of the Sylabs Singularity Enterprise suite, and is a commercial product, not open-source, so I'm afraid that documentation for it would not be included in the open-source admin docs.

**Comment by dctrud** [comment]
We are going to more consistently refer to `Sylabs Cloud` (public) and `Singularity Enterprise` (commercial paid on-premise services) in the `singularity-userdocs` to try and avoid this confusion.
