### ISSUE TITLE
Need better explanation of unprivileged singularity installation leveraging user namespaces 

### ISSUE THREAD

**Issue by GodloveD** [sylabs/singularity-admindocs#22]
Need details of how to do it and what it allows the user to do.

**Comment by TMiguelT** [comment]
Broadly, I think Singularity 3.0 needs to have an equivalent of the security section from 2.6: https://www.sylabs.io/guides/2.6/admin-guide/security.html

**Comment by GodloveD** [comment]
To clarify this issue a little, one would need to 
1. specify a custom location to install Singularity (probably in the user's home directory somewhere)
2. install without using root privs
3. set the suid workflow to `no` in the conf file
4. provide some details on how to use Singularity in unprivileged mode.  For example only sandboxes are supported.

**Comment by dctrud** [comment]
Definitely need to catch this one for the 3.5 admindocs. A user has gone to the trouble of writing it up on an issue here: https://github.com/sylabs/singularity/issues/4865

**Comment by dctrud** [comment]
Addressed the non-root / user namespace considerations in #65
