### ISSUE TITLE
Remove statement about dependencies from 3.1 section

### ISSUE THREAD

**Issue by jscook2345** [sylabs/singularity-admindocs#30]
In the `Installation` section for 3.1 docs, remove the following statement.

`Go and all other build dependencies will be downloaded automatically just to build the RPM, and will then be automatically removed.`

I don't think this applies anymore.

cc: @jmstover

**Comment by sushma-98** [comment]
It just needs to be removed or should it be replaced with something @jscook2345 ?

**Comment by devprincess** [comment]
Just opened PR 31 -> https://github.com/sylabs/singularity-admindocs/pull/31 could you verify this is correct if applicable? thank you @jscook2345
