### ISSUE TITLE
[documentation] ownership of files and configuration

### ISSUE THREAD

**Issue by vsoch** [sylabs/singularity-admindocs#39]
We are having discussion [here](https://github.com/spack/spack/pull/11094#pullrequestreview-229291140) about where (in the new docs) the content is represented that was discussed in the old docs [here](https://singularity.lbl.gov/docs-security). Specifically we are interested in issues around ownership and mode of files at install.

**Comment by vsoch** [comment]
You can look at the singularity-orb to see what works for non traditional install locations, for:
 
 - 2.x: https://github.com/singularityhub/singularity-orb/blob/master/src/orb.yml#L230
 - 3.x: https://github.com/singularityhub/singularity-orb/blob/master/src/orb.yml#L215

**Comment by dctrud** [comment]
A listing can be generated with `find . -printf "%p %u:%g %m (%M)\n"`
