### ISSUE TITLE
Admin docs for 3.0 not available, link quietly links to 2.6

### ISSUE THREAD

**Issue by kav2k** [sylabs/singularity-admindocs#4]
There are currently no Admin docs for 3.0 in any public branch.

1) This is an omission from 3.0 release. Is there a timeline for updating admin docs?

2) The main repository links to https://www.sylabs.io/guides/3.0/admin-guide/ which quietly serves 2.6 docs (because a 3.0 branch exists but is currently identical to 2.6). It should at least warn that docs for that release are not available.

**Comment by jmstover** [comment]
We actually have a start on 3.0 admin docs now!

**Comment by jmstover** [comment]
I was totally wrong in my thinking I had uploaded a 3.0 version of the admin guide ... :/

**Comment by GodloveD** [comment]
This looks fixed.  Please tell me if it is not.
