### ISSUE TITLE
Please include example directory to use for `localstatedir`

### ISSUE THREAD

**Issue by jscook2345** [sylabs/singularity-admindocs#42]
https://sylabs.io/guides/3.1/admin-guide/admin_quickstart.html#setting-localstatedir

This section of the admin guide is very well done, but it would be nice if an example or two were given based on systems we know about. IE, a single node (desktop) system, a slurm cluster, etc.

Thanks!

**Comment by dctrud** [comment]
After #65 `localstatedir` is now mentioned in:

 - Installation / Requirements / Filesystem Support
 - Installation / Compile Singularity / mconfig options
 - Quickstart / Compile & Install Singularity / mconfig options

@ikaneshiro - do you think we need do mention this further, or bring back a specific section for it? We can't really give a generic example to use for a cluster. Looking through issues we've seen NFS root dirs, overlay root dirs in newer CLE etc. so saying use `/var/lib` or similar can't be assumed to be a sensible 'local' path on a cluster.

**Comment by jmstover** [comment]
Honestly, the text: `"[...] within the local filesystem, specific to only a single host or node."`  *should* be clear enough. I would hope. :/

Building from RPM defaults to the Macro value which is usually `/var`. If you're using `./mconfig` directly it's going to default to:  `${prefix}/var`

So again... it's going to come up to exactly how the system is setup. Recommendations can be given, but... as you've said the newer CLE is messing with things, so it's going to come down to being a per site configuration option. `"specific to a single run host"` should be clear enough.

**Comment by dctrud** [comment]
@jmstover - thanks. Just wanted to confirm I wasn't being silly and missing something we could do that was obvious, to make this clearer.

**Comment by dctrud** [comment]
Closing, with multiple mentions of localstatedir at the key locations, as above - but no specific examples as we can't give any guarantee they are correct on an arbitrary system.
