### ISSUE TITLE
Describe Makefile options in installation process

### ISSUE THREAD

**Issue by jscook2345** [sylabs/singularity-admindocs#56]
Example

```
LDFLAGS, CFLAGS, CGO_ variables in build system
```

**Comment by dctrud** [comment]
@jmstover - are you aware of anyone who has used these? I'm a bit unsure about including them, lest they encourage people to think they can try and use other compilers with CGO etc.

**Comment by jmstover** [comment]
Beyond myself, no.

If you're digging around here, I would have to assume this would come down to a site specific setup, in which case the "normal" build instructions are going to be thrown out the window anyway. If you need custom linker flags, something is very different where you're building.

We luckily don't care about them to much now. Really, they may come into play when you're doing cross compiles and the like.

**Comment by dctrud** [comment]
Okay - I'm going to close this now. We can re-open if there's a specific, and potentially common, need that arises in issues etc. If we don't have this I don't think we want to encourage people to be changing the linker flags.
